<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UpazillaTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('upazillas')->insert([

            ['name'=>'Amtoli', 'division_id'=>1, 'district_id'=>1, 'sort_id'=>1, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Bamna', 'division_id'=>1, 'district_id'=>1, 'sort_id'=>2, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Barguna Sadar', 'division_id'=>1, 'district_id'=>1, 'sort_id'=>3, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Betagi', 'division_id'=>1, 'district_id'=>1, 'sort_id'=>4, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Patharghata', 'division_id'=>1, 'district_id'=>1, 'sort_id'=>5, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Taltali', 'division_id'=>1, 'district_id'=>1, 'sort_id'=>6, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],

            ['name'=>'Aigiljhara', 'division_id'=>1, 'district_id'=>2, 'sort_id'=>1, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Babuganj', 'division_id'=>1, 'district_id'=>2, 'sort_id'=>2, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Bakerganj', 'division_id'=>1, 'district_id'=>2, 'sort_id'=>3, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Banaripara', 'division_id'=>1, 'district_id'=>2, 'sort_id'=>4, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Barisal Sadar', 'division_id'=>1, 'district_id'=>2, 'sort_id'=>5, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Gournadi', 'division_id'=>1, 'district_id'=>2, 'sort_id'=>6, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Hizla', 'division_id'=>1, 'district_id'=>2, 'sort_id'=>7, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Mehendiganj', 'division_id'=>1, 'district_id'=>2, 'sort_id'=>8, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Muladi', 'division_id'=>1, 'district_id'=>2, 'sort_id'=>9, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Uzirpur', 'division_id'=>1, 'district_id'=>2, 'sort_id'=>10, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            
            ['name'=>'Bhola Sadar', 'division_id'=>1, 'district_id'=>3, 'sort_id'=>1, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Borhan Uddin', 'division_id'=>1, 'district_id'=>3, 'sort_id'=>2, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Charfashon', 'division_id'=>1, 'district_id'=>3, 'sort_id'=>3, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Daulatkhan', 'division_id'=>1, 'district_id'=>3, 'sort_id'=>4, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Lalmohan', 'division_id'=>1, 'district_id'=>3, 'sort_id'=>5, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Manpura', 'division_id'=>1, 'district_id'=>3, 'sort_id'=>6, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Tajuddin', 'division_id'=>1, 'district_id'=>3, 'sort_id'=>7, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],

            ['name'=>'Jhalkathi Sadar', 'division_id'=>1, 'district_id'=>4, 'sort_id'=>1, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Kathalia', 'division_id'=>1, 'district_id'=>4, 'sort_id'=>2, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Nalchiti', 'division_id'=>1, 'district_id'=>4, 'sort_id'=>3, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Rajapur', 'division_id'=>1, 'district_id'=>4, 'sort_id'=>4, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],

            ['name'=>'Baul', 'division_id'=>1, 'district_id'=>5, 'sort_id'=>1, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Dasmina', 'division_id'=>1, 'district_id'=>5, 'sort_id'=>2, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Dumki', 'division_id'=>1, 'district_id'=>5, 'sort_id'=>3, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Galachipa', 'division_id'=>1, 'district_id'=>5, 'sort_id'=>4, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Kalapara', 'division_id'=>1, 'district_id'=>5, 'sort_id'=>5, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Mirzaganj', 'division_id'=>1, 'district_id'=>5, 'sort_id'=>6, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Patuakhali Sadar', 'division_id'=>1, 'district_id'=>5, 'sort_id'=>7, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Rangabali', 'division_id'=>1, 'district_id'=>5, 'sort_id'=>8, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],

            ['name'=>'Bhandaria', 'division_id'=>1, 'district_id'=>6, 'sort_id'=>1, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Indorekani', 'division_id'=>1, 'district_id'=>6, 'sort_id'=>2, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Kawkhali', 'division_id'=>1, 'district_id'=>6, 'sort_id'=>3, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Mathbaria', 'division_id'=>1, 'district_id'=>6, 'sort_id'=>4, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Nazirpur', 'division_id'=>1, 'district_id'=>6, 'sort_id'=>5, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Nesarabad', 'division_id'=>1, 'district_id'=>6, 'sort_id'=>6, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Pirojpur Sadar', 'division_id'=>1, 'district_id'=>6, 'sort_id'=>7, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],

            ['name'=>'Alikadam', 'division_id'=>2, 'district_id'=>7, 'sort_id'=>1, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Bandarban Sadar', 'division_id'=>2, 'district_id'=>7, 'sort_id'=>2, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Lama', 'division_id'=>2, 'district_id'=>7, 'sort_id'=>3, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Naikhyangchari', 'division_id'=>2, 'district_id'=>7, 'sort_id'=>4, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Roangchari', 'division_id'=>2, 'district_id'=>7, 'sort_id'=>5, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Ruma', 'division_id'=>2, 'district_id'=>7, 'sort_id'=>6, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Thanchi', 'division_id'=>2, 'district_id'=>7, 'sort_id'=>7, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],

            ['name'=>'Akhaura', 'division_id'=>2, 'district_id'=>8, 'sort_id'=>1, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Ashuganj', 'division_id'=>2, 'district_id'=>8, 'sort_id'=>2, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Bansharampur', 'division_id'=>2, 'district_id'=>8, 'sort_id'=>3, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Brahmanbaria Sadar', 'division_id'=>2, 'district_id'=>8, 'sort_id'=>4, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Kasba', 'division_id'=>2, 'district_id'=>8, 'sort_id'=>5, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Nabinagar', 'division_id'=>2, 'district_id'=>8, 'sort_id'=>6, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Nasirnagar', 'division_id'=>2, 'district_id'=>8, 'sort_id'=>7, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Sareil Upazila', 'division_id'=>2, 'district_id'=>8, 'sort_id'=>8, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Vijayanagar', 'division_id'=>2, 'district_id'=>8, 'sort_id'=>9, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],

            ['name'=>'Chandpur Sadar', 'division_id'=>2, 'district_id'=>9, 'sort_id'=>1, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Faridganj', 'division_id'=>2, 'district_id'=>9, 'sort_id'=>2, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Haimchar', 'division_id'=>2, 'district_id'=>9, 'sort_id'=>3, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Hajiganj', 'division_id'=>2, 'district_id'=>9, 'sort_id'=>4, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Kachua', 'division_id'=>2, 'district_id'=>9, 'sort_id'=>5, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Matlab', 'division_id'=>2, 'district_id'=>9, 'sort_id'=>6, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Shahrasty', 'division_id'=>2, 'district_id'=>9, 'sort_id'=>7, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            
            ['name'=>'Anwara', 'division_id'=>2, 'district_id'=>10, 'sort_id'=>1, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Banskhali', 'division_id'=>2, 'district_id'=>10, 'sort_id'=>2, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Boalkhali', 'division_id'=>2, 'district_id'=>10, 'sort_id'=>3, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Chandanish', 'division_id'=>2, 'district_id'=>10, 'sort_id'=>4, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Fatikchari', 'division_id'=>2, 'district_id'=>10, 'sort_id'=>5, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Hathazari', 'division_id'=>2, 'district_id'=>10, 'sort_id'=>6, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Karnafuli', 'division_id'=>2, 'district_id'=>10, 'sort_id'=>7, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Lohagara', 'division_id'=>2, 'district_id'=>10, 'sort_id'=>8, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Mirsarai', 'division_id'=>2, 'district_id'=>10, 'sort_id'=>9, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Patiya', 'division_id'=>2, 'district_id'=>10, 'sort_id'=>10, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Rangunia', 'division_id'=>2, 'district_id'=>10, 'sort_id'=>11, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Rausan', 'division_id'=>2, 'district_id'=>10, 'sort_id'=>12, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Sandwip', 'division_id'=>2, 'district_id'=>10, 'sort_id'=>13, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Satkania', 'division_id'=>2, 'district_id'=>10, 'sort_id'=>14, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Sitakunda', 'division_id'=>2, 'district_id'=>10, 'sort_id'=>15, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            
            ['name'=>'Barura', 'division_id'=>2, 'district_id'=>11, 'sort_id'=>1, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Brahmanpara', 'division_id'=>2, 'district_id'=>11, 'sort_id'=>2, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Burichang', 'division_id'=>2, 'district_id'=>11, 'sort_id'=>3, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Chandina', 'division_id'=>2, 'district_id'=>11, 'sort_id'=>4, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Chowdogram', 'division_id'=>2, 'district_id'=>11, 'sort_id'=>5, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Comilla Sadar', 'division_id'=>2, 'district_id'=>11, 'sort_id'=>6, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Daudkandi', 'division_id'=>2, 'district_id'=>11, 'sort_id'=>7, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Devidwar', 'division_id'=>2, 'district_id'=>11, 'sort_id'=>8, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Homna', 'division_id'=>2, 'district_id'=>11, 'sort_id'=>9, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Laksam', 'division_id'=>2, 'district_id'=>11, 'sort_id'=>10, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Lalmai', 'division_id'=>2, 'district_id'=>11, 'sort_id'=>11, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Manoharganj', 'division_id'=>2, 'district_id'=>11, 'sort_id'=>12, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Meghna', 'division_id'=>2, 'district_id'=>11, 'sort_id'=>13, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Muradnagar', 'division_id'=>2, 'district_id'=>11, 'sort_id'=>14, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Nangalkot', 'division_id'=>2, 'district_id'=>11, 'sort_id'=>15, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Sadar South', 'division_id'=>2, 'district_id'=>11, 'sort_id'=>16, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Titas', 'division_id'=>2, 'district_id'=>11, 'sort_id'=>17, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            
            ['name'=>'Chakria', 'division_id'=>2, 'district_id'=>12, 'sort_id'=>1, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Cox\'s Bazar', 'division_id'=>2, 'district_id'=>12, 'sort_id'=>2, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Kutubdia', 'division_id'=>2, 'district_id'=>12, 'sort_id'=>3, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Maheshkhali', 'division_id'=>2, 'district_id'=>12, 'sort_id'=>4, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Pekua', 'division_id'=>2, 'district_id'=>12, 'sort_id'=>5, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Ramu', 'division_id'=>2, 'district_id'=>12, 'sort_id'=>6, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Teknaf', 'division_id'=>2, 'district_id'=>12, 'sort_id'=>7, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Ukhiya', 'division_id'=>2, 'district_id'=>12, 'sort_id'=>8, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            
            ['name'=>'Chaglanaiya', 'division_id'=>2, 'district_id'=>13, 'sort_id'=>1, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Daganbhumi', 'division_id'=>2, 'district_id'=>13, 'sort_id'=>2, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Feni Sadar', 'division_id'=>2, 'district_id'=>13, 'sort_id'=>3, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Parasuram', 'division_id'=>2, 'district_id'=>13, 'sort_id'=>4, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Phulgazi', 'division_id'=>2, 'district_id'=>13, 'sort_id'=>5, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Sonagazi', 'division_id'=>2, 'district_id'=>13, 'sort_id'=>6, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],

            ['name'=>'Dighinala', 'division_id'=>2, 'district_id'=>14, 'sort_id'=>1, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Guimara', 'division_id'=>2, 'district_id'=>14, 'sort_id'=>2, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Khagrachari Sadar', 'division_id'=>2, 'district_id'=>14, 'sort_id'=>3, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Lakhichari', 'division_id'=>2, 'district_id'=>14, 'sort_id'=>4, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Mahalchari', 'division_id'=>2, 'district_id'=>14, 'sort_id'=>5, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Manikchari', 'division_id'=>2, 'district_id'=>14, 'sort_id'=>6, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Matiranga', 'division_id'=>2, 'district_id'=>14, 'sort_id'=>7, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Panchari', 'division_id'=>2, 'district_id'=>14, 'sort_id'=>8, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Ramgarh', 'division_id'=>2, 'district_id'=>14, 'sort_id'=>9, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],

            ['name'=>'Kamalnagar', 'division_id'=>2, 'district_id'=>15, 'sort_id'=>1, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Lakshmipur Sadar', 'division_id'=>2, 'district_id'=>15, 'sort_id'=>2, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Raipur', 'division_id'=>2, 'district_id'=>15, 'sort_id'=>3, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Ramganj', 'division_id'=>2, 'district_id'=>15, 'sort_id'=>4, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Ramgati', 'division_id'=>2, 'district_id'=>15, 'sort_id'=>5, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],

            ['name'=>'Begamganj', 'division_id'=>2, 'district_id'=>16, 'sort_id'=>1, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Chatkhill', 'division_id'=>2, 'district_id'=>16, 'sort_id'=>2, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Companyganj', 'division_id'=>2, 'district_id'=>16, 'sort_id'=>3, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Hatia', 'division_id'=>2, 'district_id'=>16, 'sort_id'=>4, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Kabirhat', 'division_id'=>2, 'district_id'=>16, 'sort_id'=>5, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Noakhali Sadar', 'division_id'=>2, 'district_id'=>16, 'sort_id'=>6, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Senbagh', 'division_id'=>2, 'district_id'=>16, 'sort_id'=>7, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Sonimuri', 'division_id'=>2, 'district_id'=>16, 'sort_id'=>8, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Subarnchar', 'division_id'=>2, 'district_id'=>16, 'sort_id'=>9, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],

            ['name'=>'Baghaichhari', 'division_id'=>2, 'district_id'=>17, 'sort_id'=>1, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Barkal', 'division_id'=>2, 'district_id'=>17, 'sort_id'=>2, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Bilaichhari', 'division_id'=>2, 'district_id'=>17, 'sort_id'=>3, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Jurachari', 'division_id'=>2, 'district_id'=>17, 'sort_id'=>4, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Kaptai', 'division_id'=>2, 'district_id'=>17, 'sort_id'=>5, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Kawkhali', 'division_id'=>2, 'district_id'=>17, 'sort_id'=>6, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Langadu', 'division_id'=>2, 'district_id'=>17, 'sort_id'=>7, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Nanyarchar', 'division_id'=>2, 'district_id'=>17, 'sort_id'=>8, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Rajasthali', 'division_id'=>2, 'district_id'=>17, 'sort_id'=>9, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Rangamati Sadar', 'division_id'=>2, 'district_id'=>17, 'sort_id'=>10, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],

            ['name'=>'Dhamrai', 'division_id'=>3, 'district_id'=>18, 'sort_id'=>1, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Dohar', 'division_id'=>3, 'district_id'=>18, 'sort_id'=>2, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Keraniganj', 'division_id'=>3, 'district_id'=>18, 'sort_id'=>3, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Nawabganj', 'division_id'=>3, 'district_id'=>18, 'sort_id'=>4, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Savar', 'division_id'=>3, 'district_id'=>18, 'sort_id'=>5, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],

            ['name'=>'Alphadanga', 'division_id'=>3, 'district_id'=>19, 'sort_id'=>1, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Boalmari', 'division_id'=>3, 'district_id'=>19, 'sort_id'=>2, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Bangga', 'division_id'=>3, 'district_id'=>19, 'sort_id'=>3, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Charbhadrasan', 'division_id'=>3, 'district_id'=>19, 'sort_id'=>4, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Faridpur Sadar', 'division_id'=>3, 'district_id'=>19, 'sort_id'=>5, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Madhukhali', 'division_id'=>3, 'district_id'=>19, 'sort_id'=>6, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Nagarkanda', 'division_id'=>3, 'district_id'=>19, 'sort_id'=>7, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Sadarpur', 'division_id'=>3, 'district_id'=>19, 'sort_id'=>8, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Saltha', 'division_id'=>3, 'district_id'=>19, 'sort_id'=>9, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],

            ['name'=>'Gazipur Sadar', 'division_id'=>3, 'district_id'=>20, 'sort_id'=>1, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Kaliakir', 'division_id'=>3, 'district_id'=>20, 'sort_id'=>2, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Kaliganj', 'division_id'=>3, 'district_id'=>20, 'sort_id'=>3, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Kapasia', 'division_id'=>3, 'district_id'=>20, 'sort_id'=>4, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Sripur', 'division_id'=>3, 'district_id'=>20, 'sort_id'=>5, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],

            ['name'=>'Gopalganj Sadar', 'division_id'=>3, 'district_id'=>21, 'sort_id'=>1, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Kashiani', 'division_id'=>3, 'district_id'=>21, 'sort_id'=>2, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Kotalipara', 'division_id'=>3, 'district_id'=>21, 'sort_id'=>3, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Maksudpur', 'division_id'=>3, 'district_id'=>21, 'sort_id'=>4, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Tungipara', 'division_id'=>3, 'district_id'=>21, 'sort_id'=>5, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],

            ['name'=>'Ashtagram', 'division_id'=>3, 'district_id'=>22, 'sort_id'=>1, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Bajitpur', 'division_id'=>3, 'district_id'=>22, 'sort_id'=>2, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Bhairab', 'division_id'=>3, 'district_id'=>22, 'sort_id'=>3, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Etna', 'division_id'=>3, 'district_id'=>22, 'sort_id'=>4, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Hossainpur', 'division_id'=>3, 'district_id'=>22, 'sort_id'=>5, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Karimganj', 'division_id'=>3, 'district_id'=>22, 'sort_id'=>6, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Katiadi', 'division_id'=>3, 'district_id'=>22, 'sort_id'=>7, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Kishoreganj Sadar', 'division_id'=>3, 'district_id'=>22, 'sort_id'=>8, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Kuliarchar', 'division_id'=>3, 'district_id'=>22, 'sort_id'=>9, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Mithamoin', 'division_id'=>3, 'district_id'=>22, 'sort_id'=>10, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Nikli', 'division_id'=>3, 'district_id'=>22, 'sort_id'=>11, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Pakundia', 'division_id'=>3, 'district_id'=>22, 'sort_id'=>12, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Tarail', 'division_id'=>3, 'district_id'=>22, 'sort_id'=>13, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],

            ['name'=>'Kalkini', 'division_id'=>3, 'district_id'=>23, 'sort_id'=>1, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Madaripur Sadar', 'division_id'=>3, 'district_id'=>23, 'sort_id'=>2, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Rajaire', 'division_id'=>3, 'district_id'=>23, 'sort_id'=>3, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Shivchar', 'division_id'=>3, 'district_id'=>23, 'sort_id'=>4, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],

            ['name'=>'Daulatpur', 'division_id'=>3, 'district_id'=>24, 'sort_id'=>1, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Gheore', 'division_id'=>3, 'district_id'=>24, 'sort_id'=>2, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Horirampur', 'division_id'=>3, 'district_id'=>24, 'sort_id'=>3, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Manikganj Sadar', 'division_id'=>3, 'district_id'=>24, 'sort_id'=>4, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Saturia', 'division_id'=>3, 'district_id'=>24, 'sort_id'=>5, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Shiblaya', 'division_id'=>3, 'district_id'=>24, 'sort_id'=>6, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Singhair', 'division_id'=>3, 'district_id'=>24, 'sort_id'=>7, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],

            ['name'=>'Gazaria', 'division_id'=>3, 'district_id'=>25, 'sort_id'=>1, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Lauhajang', 'division_id'=>3, 'district_id'=>25, 'sort_id'=>2, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Munshiganj Sadar', 'division_id'=>3, 'district_id'=>25, 'sort_id'=>3, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Srinagar', 'division_id'=>3, 'district_id'=>25, 'sort_id'=>4, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Sirajdikhan', 'division_id'=>3, 'district_id'=>25, 'sort_id'=>5, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'tangibari', 'division_id'=>3, 'district_id'=>25, 'sort_id'=>6, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],

            ['name'=>'Araihazar', 'division_id'=>3, 'district_id'=>26, 'sort_id'=>1, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Bandar', 'division_id'=>3, 'district_id'=>26, 'sort_id'=>2, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Narayanganj Sadar', 'division_id'=>3, 'district_id'=>26, 'sort_id'=>3, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Rupganj', 'division_id'=>3, 'district_id'=>26, 'sort_id'=>4, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Sonargaon', 'division_id'=>3, 'district_id'=>26, 'sort_id'=>5, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],

            ['name'=>'Belabo', 'division_id'=>3, 'district_id'=>27, 'sort_id'=>1, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Manohardi', 'division_id'=>3, 'district_id'=>27, 'sort_id'=>2, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Narsingdi Sadar', 'division_id'=>3, 'district_id'=>27, 'sort_id'=>3, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Palash', 'division_id'=>3, 'district_id'=>27, 'sort_id'=>4, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Raipura', 'division_id'=>3, 'district_id'=>27, 'sort_id'=>5, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Shivpur', 'division_id'=>3, 'district_id'=>27, 'sort_id'=>6, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],

            ['name'=>'Baliyakandi', 'division_id'=>3, 'district_id'=>28, 'sort_id'=>1, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Goalanda', 'division_id'=>3, 'district_id'=>28, 'sort_id'=>2, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Kalukhali', 'division_id'=>3, 'district_id'=>28, 'sort_id'=>3, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Pansha', 'division_id'=>3, 'district_id'=>28, 'sort_id'=>4, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Rajbari Sadar', 'division_id'=>3, 'district_id'=>28, 'sort_id'=>5, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],

            ['name'=>'Basile', 'division_id'=>3, 'district_id'=>29, 'sort_id'=>1, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Bhuapur', 'division_id'=>3, 'district_id'=>29, 'sort_id'=>2, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Delduar', 'division_id'=>3, 'district_id'=>29, 'sort_id'=>3, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Dhanbari', 'division_id'=>3, 'district_id'=>29, 'sort_id'=>4, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Ghatail', 'division_id'=>3, 'district_id'=>29, 'sort_id'=>5, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Gopalpur', 'division_id'=>3, 'district_id'=>29, 'sort_id'=>6, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Kalihati', 'division_id'=>3, 'district_id'=>29, 'sort_id'=>7, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Madhupur', 'division_id'=>3, 'district_id'=>29, 'sort_id'=>8, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Mirzapur', 'division_id'=>3, 'district_id'=>29, 'sort_id'=>9, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Nagarpur', 'division_id'=>3, 'district_id'=>29, 'sort_id'=>10, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Sakhipur', 'division_id'=>3, 'district_id'=>29, 'sort_id'=>11, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Tangail Sadar', 'division_id'=>3, 'district_id'=>29, 'sort_id'=>12, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],

            ['name'=>'Damuda', 'division_id'=>3, 'district_id'=>30, 'sort_id'=>1, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Gosairhat', 'division_id'=>3, 'district_id'=>30, 'sort_id'=>2, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Jazira', 'division_id'=>3, 'district_id'=>30, 'sort_id'=>3, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Nadia', 'division_id'=>3, 'district_id'=>30, 'sort_id'=>4, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Shariatpur Sadar', 'division_id'=>3, 'district_id'=>30, 'sort_id'=>5, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Vedarganj', 'division_id'=>3, 'district_id'=>30, 'sort_id'=>6, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            
            // Khulna division --- Bagerhat district
            ['name'=>'Bagerhat Sadar', 'division_id'=>4, 'district_id'=>31, 'sort_id'=>1, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Chitalamari', 'division_id'=>4, 'district_id'=>31, 'sort_id'=>2, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Fakirhat', 'division_id'=>4, 'district_id'=>31, 'sort_id'=>3, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Kachua', 'division_id'=>4, 'district_id'=>31, 'sort_id'=>4, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Mollahat', 'division_id'=>4, 'district_id'=>31, 'sort_id'=>5, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Mongla', 'division_id'=>4, 'district_id'=>31, 'sort_id'=>6, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Morelganj', 'division_id'=>4, 'district_id'=>31, 'sort_id'=>7, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Rampal', 'division_id'=>4, 'district_id'=>31, 'sort_id'=>8, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Sharankhola', 'division_id'=>4, 'district_id'=>31, 'sort_id'=>9, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            
            // Khulna division --- Chuadanga district
            ['name'=>'Alamdanga', 'division_id'=>4, 'district_id'=>32, 'sort_id'=>1, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Chuadanga Headquarters', 'division_id'=>4, 'district_id'=>32, 'sort_id'=>2, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Damurhuda', 'division_id'=>4, 'district_id'=>32, 'sort_id'=>3, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Jivanagar', 'division_id'=>4, 'district_id'=>32, 'sort_id'=>4, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],

            // Khulna division --- Jessore district
            ['name'=>'Abhaynagar', 'division_id'=>4, 'district_id'=>33, 'sort_id'=>1, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Bagharpara', 'division_id'=>4, 'district_id'=>33, 'sort_id'=>2, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Chowgacha', 'division_id'=>4, 'district_id'=>33, 'sort_id'=>3, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Jessore Sadar', 'division_id'=>4, 'district_id'=>33, 'sort_id'=>4, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Jhikargachha', 'division_id'=>4, 'district_id'=>33, 'sort_id'=>5, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Keshabpur', 'division_id'=>4, 'district_id'=>33, 'sort_id'=>6, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Manirampur', 'division_id'=>4, 'district_id'=>33, 'sort_id'=>7, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Sharsha', 'division_id'=>4, 'district_id'=>33, 'sort_id'=>8, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],

            // Khulna division --- Jhenaidah district
            ['name'=>'Haryanakundu', 'division_id'=>4, 'district_id'=>34, 'sort_id'=>1, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Jhenaidah Sadar', 'division_id'=>4, 'district_id'=>34, 'sort_id'=>2, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Kotchandpur', 'division_id'=>4, 'district_id'=>34, 'sort_id'=>3, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Kaliganj', 'division_id'=>4, 'district_id'=>34, 'sort_id'=>4, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Maheshpur', 'division_id'=>4, 'district_id'=>34, 'sort_id'=>5, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Shailkupa', 'division_id'=>4, 'district_id'=>34, 'sort_id'=>6, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],

            // Khulna division --- Khulna district
            ['name'=>'Batiaghata', 'division_id'=>4, 'district_id'=>35, 'sort_id'=>1, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Dakopa', 'division_id'=>4, 'district_id'=>35, 'sort_id'=>2, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Dighalia', 'division_id'=>4, 'district_id'=>35, 'sort_id'=>3, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Dumuria', 'division_id'=>4, 'district_id'=>35, 'sort_id'=>4, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Fultala', 'division_id'=>4, 'district_id'=>35, 'sort_id'=>5, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'koyra', 'division_id'=>4, 'district_id'=>35, 'sort_id'=>6, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Paikgachha', 'division_id'=>4, 'district_id'=>35, 'sort_id'=>7, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Rupsa', 'division_id'=>4, 'district_id'=>35, 'sort_id'=>8, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Terakhada', 'division_id'=>4, 'district_id'=>35, 'sort_id'=>9, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],

            // Khulna division --- Kushtia district
            ['name'=>'Bheramara', 'division_id'=>4, 'district_id'=>36, 'sort_id'=>1, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Daulatpur', 'division_id'=>4, 'district_id'=>36, 'sort_id'=>2, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Khoksa', 'division_id'=>4, 'district_id'=>36, 'sort_id'=>3, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Kumarakhali', 'division_id'=>4, 'district_id'=>36, 'sort_id'=>4, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Kushtia Sadar', 'division_id'=>4, 'district_id'=>36, 'sort_id'=>5, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Mirpur', 'division_id'=>4, 'district_id'=>36, 'sort_id'=>6, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],

            // Khulna division --- Magura district
            ['name'=>'Mohammadpur', 'division_id'=>4, 'district_id'=>37, 'sort_id'=>1, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Magura Sadar', 'division_id'=>4, 'district_id'=>37, 'sort_id'=>2, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Salika', 'division_id'=>4, 'district_id'=>37, 'sort_id'=>3, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Sripur', 'division_id'=>4, 'district_id'=>37, 'sort_id'=>4, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],

            // Khulna division --- Meherpur district
            ['name'=>'Gangni', 'division_id'=>4, 'district_id'=>38, 'sort_id'=>1, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Meherpur Sadar', 'division_id'=>4, 'district_id'=>38, 'sort_id'=>2, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Mujibnagar', 'division_id'=>4, 'district_id'=>38, 'sort_id'=>3, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],

            // Khulna division --- Narail district
            ['name'=>'Kalia', 'division_id'=>4, 'district_id'=>39, 'sort_id'=>1, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Lohagara', 'division_id'=>4, 'district_id'=>39, 'sort_id'=>2, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Narail Sadar', 'division_id'=>4, 'district_id'=>39, 'sort_id'=>3, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],

            // Khulna division --- Satkhira district
            ['name'=>'Ashashuni', 'division_id'=>4, 'district_id'=>40, 'sort_id'=>1, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Debhata', 'division_id'=>4, 'district_id'=>40, 'sort_id'=>2, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Kaliganj', 'division_id'=>4, 'district_id'=>40, 'sort_id'=>3, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Kalroa', 'division_id'=>4, 'district_id'=>40, 'sort_id'=>4, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Satkhira Sadar', 'division_id'=>4, 'district_id'=>40, 'sort_id'=>5, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Shamnagar', 'division_id'=>4, 'district_id'=>40, 'sort_id'=>6, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Tala', 'division_id'=>4, 'district_id'=>40, 'sort_id'=>7, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],

            // Mymensingh division --- Jamalpur district
            ['name'=>'Bakshiganj', 'division_id'=>5, 'district_id'=>41, 'sort_id'=>1, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Dewanganj', 'division_id'=>5, 'district_id'=>41, 'sort_id'=>2, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Islampur', 'division_id'=>5, 'district_id'=>41, 'sort_id'=>3, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Jamalpur Sadar', 'division_id'=>5, 'district_id'=>41, 'sort_id'=>4, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Madarganj', 'division_id'=>5, 'district_id'=>41, 'sort_id'=>5, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Melandah', 'division_id'=>5, 'district_id'=>41, 'sort_id'=>6, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Sarisabari', 'division_id'=>5, 'district_id'=>41, 'sort_id'=>7, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],

            // Mymensingh division --- Mymensingh district
            ['name'=>'Bhaluka', 'division_id'=>5, 'district_id'=>42, 'sort_id'=>1, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Dhobaur', 'division_id'=>5, 'district_id'=>42, 'sort_id'=>2, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Gauripur', 'division_id'=>5, 'district_id'=>42, 'sort_id'=>3, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Gopargaon', 'division_id'=>5, 'district_id'=>42, 'sort_id'=>4, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Halua Ghat', 'division_id'=>5, 'district_id'=>42, 'sort_id'=>5, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Ishwarganj', 'division_id'=>5, 'district_id'=>42, 'sort_id'=>6, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Muktagacha', 'division_id'=>5, 'district_id'=>42, 'sort_id'=>7, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Mymensingh Sadar', 'division_id'=>5, 'district_id'=>42, 'sort_id'=>8, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Nandail', 'division_id'=>5, 'district_id'=>42, 'sort_id'=>9, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Phulbaria', 'division_id'=>5, 'district_id'=>42, 'sort_id'=>10, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Phulpur', 'division_id'=>5, 'district_id'=>42, 'sort_id'=>11, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Tarakanda', 'division_id'=>5, 'district_id'=>42, 'sort_id'=>12, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Trishal', 'division_id'=>5, 'district_id'=>42, 'sort_id'=>13, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],

            // Mymensingh division --- Netrokona district
            ['name'=>'Atpara', 'division_id'=>5, 'district_id'=>43, 'sort_id'=>1, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Barhatta', 'division_id'=>5, 'district_id'=>43, 'sort_id'=>2, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Durgapur', 'division_id'=>5, 'district_id'=>43, 'sort_id'=>3, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Kalmakandha', 'division_id'=>5, 'district_id'=>43, 'sort_id'=>4, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Kendua', 'division_id'=>5, 'district_id'=>43, 'sort_id'=>5, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Khaliajuri', 'division_id'=>5, 'district_id'=>43, 'sort_id'=>6, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Madan', 'division_id'=>5, 'district_id'=>43, 'sort_id'=>7, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Mohanganj', 'division_id'=>5, 'district_id'=>43, 'sort_id'=>8, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Netrokona Sadar', 'division_id'=>5, 'district_id'=>43, 'sort_id'=>9, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Purbo Dholla', 'division_id'=>5, 'district_id'=>43, 'sort_id'=>10, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],

            // Mymensingh division --- Netrokona district
            ['name'=>'Jhenaigati', 'division_id'=>5, 'district_id'=>44, 'sort_id'=>1, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Nakla', 'division_id'=>5, 'district_id'=>44, 'sort_id'=>2, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Nalitbari', 'division_id'=>5, 'district_id'=>44, 'sort_id'=>3, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Sherpur', 'division_id'=>5, 'district_id'=>44, 'sort_id'=>4, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Shribardi', 'division_id'=>5, 'district_id'=>44, 'sort_id'=>5, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            // ,  ,  ,  , ,  ,  ,   ,  ,  ,  , 
            // Rajshahi division --- Bogra district
            ['name'=>'Adamdighi', 'division_id'=>6, 'district_id'=>45, 'sort_id'=>1, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Bogra Sadar', 'division_id'=>6, 'district_id'=>45, 'sort_id'=>2, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Dhunat', 'division_id'=>6, 'district_id'=>45, 'sort_id'=>3, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Dupachacia', 'division_id'=>6, 'district_id'=>45, 'sort_id'=>4, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Gabtali', 'division_id'=>6, 'district_id'=>45, 'sort_id'=>5, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Kahalu', 'division_id'=>6, 'district_id'=>45, 'sort_id'=>6, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Nandigram', 'division_id'=>6, 'district_id'=>45, 'sort_id'=>7, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Shajahanpur', 'division_id'=>6, 'district_id'=>45, 'sort_id'=>8, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Sherpur', 'division_id'=>6, 'district_id'=>45, 'sort_id'=>9, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Sariakandi', 'division_id'=>6, 'district_id'=>45, 'sort_id'=>10, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Shibganj', 'division_id'=>6, 'district_id'=>45, 'sort_id'=>11, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Sonatola', 'division_id'=>6, 'district_id'=>45, 'sort_id'=>12, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],

            // Rajshahi division --- Chapainawabganj district
            ['name'=>'Bholahat', 'division_id'=>6, 'district_id'=>46, 'sort_id'=>1, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Chapainawabganj Sadar', 'division_id'=>6, 'district_id'=>46, 'sort_id'=>2, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Gomstapur', 'division_id'=>6, 'district_id'=>46, 'sort_id'=>3, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Nachol', 'division_id'=>6, 'district_id'=>46, 'sort_id'=>4, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Shibganj', 'division_id'=>6, 'district_id'=>46, 'sort_id'=>5, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],

            // Rajshahi division --- Chapainawabganj district
            ['name'=>'Akkelpur', 'division_id'=>6, 'district_id'=>47, 'sort_id'=>1, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Joypurhat Sadar', 'division_id'=>6, 'district_id'=>47, 'sort_id'=>2, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Kalai', 'division_id'=>6, 'district_id'=>47, 'sort_id'=>3, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Khetlal', 'division_id'=>6, 'district_id'=>47, 'sort_id'=>4, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Panchbibi', 'division_id'=>6, 'district_id'=>47, 'sort_id'=>5, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],

            // Rajshahi division --- Bogra district
            ['name'=>'Atrai', 'division_id'=>6, 'district_id'=>48, 'sort_id'=>1, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Badalgachi', 'division_id'=>6, 'district_id'=>48, 'sort_id'=>2, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Dhamirhat', 'division_id'=>6, 'district_id'=>48, 'sort_id'=>3, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Mahadebpur', 'division_id'=>6, 'district_id'=>48, 'sort_id'=>4, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Manda', 'division_id'=>6, 'district_id'=>48, 'sort_id'=>5, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Niamatpur', 'division_id'=>6, 'district_id'=>48, 'sort_id'=>6, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Naogaon Sadar', 'division_id'=>6, 'district_id'=>48, 'sort_id'=>7, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Patarkhla', 'division_id'=>6, 'district_id'=>48, 'sort_id'=>8, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Porsha', 'division_id'=>6, 'district_id'=>48, 'sort_id'=>9, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Raninagar', 'division_id'=>6, 'district_id'=>48, 'sort_id'=>10, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Sapahar', 'division_id'=>6, 'district_id'=>48, 'sort_id'=>11, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],

            // Rajshahi division --- Natore district
            ['name'=>'Bagatipara', 'division_id'=>6, 'district_id'=>49, 'sort_id'=>1, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Barigram', 'division_id'=>6, 'district_id'=>49, 'sort_id'=>2, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Gurdaspur', 'division_id'=>6, 'district_id'=>49, 'sort_id'=>3, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Lalpur', 'division_id'=>6, 'district_id'=>49, 'sort_id'=>4, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Natore Sadar', 'division_id'=>6, 'district_id'=>49, 'sort_id'=>5, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Noldanga', 'division_id'=>6, 'district_id'=>49, 'sort_id'=>6, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Singra', 'division_id'=>6, 'district_id'=>49, 'sort_id'=>7, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],

            // Rajshahi division --- Pabna district
            ['name'=>'Atgharia', 'division_id'=>6, 'district_id'=>50, 'sort_id'=>1, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Bhangra', 'division_id'=>6, 'district_id'=>50, 'sort_id'=>2, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Bera', 'division_id'=>6, 'district_id'=>50, 'sort_id'=>3, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Chatmohar', 'division_id'=>6, 'district_id'=>50, 'sort_id'=>4, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Faridpur', 'division_id'=>6, 'district_id'=>50, 'sort_id'=>5, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Ishwardi', 'division_id'=>6, 'district_id'=>50, 'sort_id'=>6, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Pabna Sadar', 'division_id'=>6, 'district_id'=>50, 'sort_id'=>7, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Shathia', 'division_id'=>6, 'district_id'=>50, 'sort_id'=>8, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Sujanagar', 'division_id'=>6, 'district_id'=>50, 'sort_id'=>9, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],

            // Rajshahi division --- Rajshahi district
            ['name'=>'Bagha', 'division_id'=>6, 'district_id'=>51, 'sort_id'=>1, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Bagmara', 'division_id'=>6, 'district_id'=>51, 'sort_id'=>2, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Charghat', 'division_id'=>6, 'district_id'=>51, 'sort_id'=>3, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Durgapur', 'division_id'=>6, 'district_id'=>51, 'sort_id'=>4, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Godagari', 'division_id'=>6, 'district_id'=>51, 'sort_id'=>5, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Mohanpur', 'division_id'=>6, 'district_id'=>51, 'sort_id'=>6, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Poba', 'division_id'=>6, 'district_id'=>51, 'sort_id'=>7, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Puthia', 'division_id'=>6, 'district_id'=>51, 'sort_id'=>8, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Tanar', 'division_id'=>6, 'district_id'=>51, 'sort_id'=>9, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],


            // Rajshahi division --- Sirajganj district
            ['name'=>'Belkuchi', 'division_id'=>6, 'district_id'=>52, 'sort_id'=>1, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Chowhali', 'division_id'=>6, 'district_id'=>52, 'sort_id'=>2, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Kamarkhand', 'division_id'=>6, 'district_id'=>52, 'sort_id'=>3, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Kazipur', 'division_id'=>6, 'district_id'=>52, 'sort_id'=>4, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Raiganj', 'division_id'=>6, 'district_id'=>52, 'sort_id'=>5, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Shahzadpur', 'division_id'=>6, 'district_id'=>52, 'sort_id'=>6, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Sirajganj Sadar', 'division_id'=>6, 'district_id'=>52, 'sort_id'=>7, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Tarash', 'division_id'=>6, 'district_id'=>52, 'sort_id'=>8, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Ullapara', 'division_id'=>6, 'district_id'=>52, 'sort_id'=>9, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],

            // Rangpur division --- Dinajpur district
            ['name'=>'Birganj', 'division_id'=>7, 'district_id'=>53, 'sort_id'=>1, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Birampur', 'division_id'=>7, 'district_id'=>53, 'sort_id'=>2, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Bochaganj', 'division_id'=>7, 'district_id'=>53, 'sort_id'=>3, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Chirirbandar', 'division_id'=>7, 'district_id'=>53, 'sort_id'=>4, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Dinajpur Sadar', 'division_id'=>7, 'district_id'=>53, 'sort_id'=>5, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Ghoraghat', 'division_id'=>7, 'district_id'=>53, 'sort_id'=>6, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Hakimpur', 'division_id'=>7, 'district_id'=>53, 'sort_id'=>7, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Kaharole', 'division_id'=>7, 'district_id'=>53, 'sort_id'=>8, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Khansama', 'division_id'=>7, 'district_id'=>53, 'sort_id'=>9, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Nawabganj', 'division_id'=>7, 'district_id'=>53, 'sort_id'=>10, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Parbatipur', 'division_id'=>7, 'district_id'=>53, 'sort_id'=>11, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Phulbari', 'division_id'=>7, 'district_id'=>53, 'sort_id'=>12, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Birol', 'division_id'=>7, 'district_id'=>53, 'sort_id'=>13, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],

            // Rangpur division --- Gaibandha district
            ['name'=>'Gaibandha Sadar', 'division_id'=>7, 'district_id'=>54, 'sort_id'=>1, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Gobindganj', 'division_id'=>7, 'district_id'=>54, 'sort_id'=>2, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Palashbari', 'division_id'=>7, 'district_id'=>54, 'sort_id'=>3, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Phulchari', 'division_id'=>7, 'district_id'=>54, 'sort_id'=>4, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Sadullapur', 'division_id'=>7, 'district_id'=>54, 'sort_id'=>5, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Saghata', 'division_id'=>7, 'district_id'=>54, 'sort_id'=>6, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Sundarganj', 'division_id'=>7, 'district_id'=>54, 'sort_id'=>7, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],

            // Rangpur division --- Kurigram district
            ['name'=>'Bhurungamari', 'division_id'=>7, 'district_id'=>55, 'sort_id'=>1, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Char Rajibpur', 'division_id'=>7, 'district_id'=>55, 'sort_id'=>2, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Chilmari', 'division_id'=>7, 'district_id'=>55, 'sort_id'=>3, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Kurigram Sadar', 'division_id'=>7, 'district_id'=>55, 'sort_id'=>4, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Nageshwari', 'division_id'=>7, 'district_id'=>55, 'sort_id'=>5, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Phulbari', 'division_id'=>7, 'district_id'=>55, 'sort_id'=>6, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Rajarhat', 'division_id'=>7, 'district_id'=>55, 'sort_id'=>7, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Roumari', 'division_id'=>7, 'district_id'=>55, 'sort_id'=>8, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Ulipur', 'division_id'=>7, 'district_id'=>55, 'sort_id'=>9, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],

            // Rangpur division --- Lalmonirhat district
            ['name'=>'Aditmari', 'division_id'=>7, 'district_id'=>56, 'sort_id'=>1, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Hattibandha', 'division_id'=>7, 'district_id'=>56, 'sort_id'=>2, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Lalmonirhat Sadar', 'division_id'=>7, 'district_id'=>56, 'sort_id'=>3, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'KKaliganj', 'division_id'=>7, 'district_id'=>56, 'sort_id'=>4, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Patgra', 'division_id'=>7, 'district_id'=>56, 'sort_id'=>5, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],

            // Rangpur division --- Nilphamari district
            ['name'=>'Dimla', 'division_id'=>7, 'district_id'=>57, 'sort_id'=>1, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Domar', 'division_id'=>7, 'district_id'=>57, 'sort_id'=>2, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Jalika', 'division_id'=>7, 'district_id'=>57, 'sort_id'=>3, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Kishoreganj', 'division_id'=>7, 'district_id'=>57, 'sort_id'=>4, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Nilphamari Sadar', 'division_id'=>7, 'district_id'=>57, 'sort_id'=>5, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Saidpur', 'division_id'=>7, 'district_id'=>57, 'sort_id'=>6, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],

            // Rangpur division --- Panchagarh district
            ['name'=>'Atwari', 'division_id'=>7, 'district_id'=>58, 'sort_id'=>1, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Bhora', 'division_id'=>7, 'district_id'=>58, 'sort_id'=>2, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Deviganj', 'division_id'=>7, 'district_id'=>58, 'sort_id'=>3, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Panchagarh', 'division_id'=>7, 'district_id'=>58, 'sort_id'=>4, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Tetulia', 'division_id'=>7, 'district_id'=>58, 'sort_id'=>5, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],

            // Rangpur division --- Rangpur district
            ['name'=>'Badarganj', 'division_id'=>7, 'district_id'=>59, 'sort_id'=>1, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Gongachara', 'division_id'=>7, 'district_id'=>59, 'sort_id'=>2, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Kaunia', 'division_id'=>7, 'district_id'=>59, 'sort_id'=>3, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Mithapukur', 'division_id'=>7, 'district_id'=>59, 'sort_id'=>4, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Pirgacha', 'division_id'=>7, 'district_id'=>59, 'sort_id'=>5, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Pirganj', 'division_id'=>7, 'district_id'=>59, 'sort_id'=>6, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Rangpur Sadar', 'division_id'=>7, 'district_id'=>59, 'sort_id'=>7, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Taraganj', 'division_id'=>7, 'district_id'=>59, 'sort_id'=>8, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],

            // Rangpur division --- hakurgaon district
            ['name'=>'Baliadangi', 'division_id'=>7, 'district_id'=>60, 'sort_id'=>1, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Haripur', 'division_id'=>7, 'district_id'=>60, 'sort_id'=>2, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Pirganj', 'division_id'=>7, 'district_id'=>60, 'sort_id'=>3, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Ranishankail', 'division_id'=>7, 'district_id'=>60, 'sort_id'=>4, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'hakurgaon Sadar', 'division_id'=>7, 'district_id'=>60, 'sort_id'=>5, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],

            // Sylhet division --- Habiganj district
            ['name'=>'Azmiriganj', 'division_id'=>8, 'district_id'=>61, 'sort_id'=>1, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Bahubal', 'division_id'=>8, 'district_id'=>61, 'sort_id'=>2, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Baniachang', 'division_id'=>8, 'district_id'=>61, 'sort_id'=>3, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Chunarughat', 'division_id'=>8, 'district_id'=>61, 'sort_id'=>4, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Habiganj Sadar', 'division_id'=>8, 'district_id'=>61, 'sort_id'=>5, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Lakhai', 'division_id'=>8, 'district_id'=>61, 'sort_id'=>6, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Madhabpur', 'division_id'=>8, 'district_id'=>61, 'sort_id'=>7, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Nabiganj', 'division_id'=>8, 'district_id'=>61, 'sort_id'=>8, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Shaistaganj', 'division_id'=>8, 'district_id'=>61, 'sort_id'=>9, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],

            // Sylhet division --- Habiganj district
            ['name'=>'Barlekha', 'division_id'=>8, 'district_id'=>62, 'sort_id'=>1, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Juri', 'division_id'=>8, 'district_id'=>62, 'sort_id'=>2, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Kamalganj', 'division_id'=>8, 'district_id'=>62, 'sort_id'=>3, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Kulaura', 'division_id'=>8, 'district_id'=>62, 'sort_id'=>4, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Moulvibazar Sadar', 'division_id'=>8, 'district_id'=>62, 'sort_id'=>5, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Rajnagar ', 'division_id'=>8, 'district_id'=>62, 'sort_id'=>6, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Srimangal', 'division_id'=>8, 'district_id'=>62, 'sort_id'=>7, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],

            // Sylhet division --- Sunamganj district
            ['name'=>'Chhatak', 'division_id'=>8, 'district_id'=>63, 'sort_id'=>1, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Dharmapasha', 'division_id'=>8, 'district_id'=>63, 'sort_id'=>2, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Dirai', 'division_id'=>8, 'district_id'=>63, 'sort_id'=>3, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Doarabazar', 'division_id'=>8, 'district_id'=>63, 'sort_id'=>4, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Dokkhin Sunamganj', 'division_id'=>8, 'district_id'=>63, 'sort_id'=>5, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Jagannathpur', 'division_id'=>8, 'district_id'=>63, 'sort_id'=>6, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Jamalganj', 'division_id'=>8, 'district_id'=>63, 'sort_id'=>7, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Shala', 'division_id'=>8, 'district_id'=>63, 'sort_id'=>8, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Sunamganj Sadar', 'division_id'=>8, 'district_id'=>63, 'sort_id'=>9, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Tahirpur', 'division_id'=>8, 'district_id'=>63, 'sort_id'=>10, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Viswanamburpur', 'division_id'=>8, 'district_id'=>63, 'sort_id'=>11, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],

            // Sylhet division --- Sylhet district
            ['name'=>'Balaganj', 'division_id'=>8, 'district_id'=>64, 'sort_id'=>1, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Bianibazar', 'division_id'=>8, 'district_id'=>64, 'sort_id'=>2, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Companyganj', 'division_id'=>8, 'district_id'=>64, 'sort_id'=>3, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Dokkhin Surma', 'division_id'=>8, 'district_id'=>64, 'sort_id'=>4, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'fenchuganj', 'division_id'=>8, 'district_id'=>64, 'sort_id'=>5, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Gopalganj', 'division_id'=>8, 'district_id'=>64, 'sort_id'=>6, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Gowainghat', 'division_id'=>8, 'district_id'=>64, 'sort_id'=>7, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Jaintiapur', 'division_id'=>8, 'district_id'=>64, 'sort_id'=>8, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Kanaighat', 'division_id'=>8, 'district_id'=>64, 'sort_id'=>9, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Osmani', 'division_id'=>8, 'district_id'=>64, 'sort_id'=>10, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Sylhet Sadar', 'division_id'=>8, 'district_id'=>64, 'sort_id'=>11, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'Vishwanath', 'division_id'=>8, 'district_id'=>64, 'sort_id'=>12, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            ['name'=>'zakiganj', 'division_id'=>8, 'district_id'=>64, 'sort_id'=>13, 'created_at'=>date("Y-m-d H:i:s"), 'updated_at'=>date("Y-m-d H:i:s"), 'created_by'=>1, 'updated_by'=>1],
            
        ]);
    }
}
