<template>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <ul class="nav nav-pills" id="pills-tab" role="tablist">
                            <li class="nav-item">
                                <a class="nav-link" id="pills-world-tab" data-toggle="pill" href="#pills-world" role="tab" aria-controls="pills-world" aria-selected="false">World</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link active" id="pills-bd-tab" data-toggle="pill" href="#pills-bd" role="tab" aria-controls="pills-bd" aria-selected="true">Bangladesh</a>
                            </li>
                        </ul>
                    </div>

                    <div class="card-body">

                        <div class="tab-content" id="pills-tabContent">

                            <div class="tab-pane fade" id="pills-world" role="tabpanel" aria-labelledby="pills-world-tab">
                                <img src="assets/img/world-map.png" usemap="#image-world-map">
                            </div>

                            <div class="tab-pane fade show active" id="pills-bd" role="tabpanel" aria-labelledby="pills-bd-tab">
                                <div class="row justify-content-center">
                                    
                                    <div class="col-6">
                                        <!-- Image Map Generated by http://www.image-map.net/ -->
                                        <img src="assets/img/bd-cc-map.png" usemap="#image-bd-cc-map">

                                        <map name="image-bd-cc-map">
                                            <area target="" @click.prevent="ccDetails" alt="Barishal City Corporation" title="Barishal City Corporation" href="/mahanagar/1" coords="176,442,172,417,178,394,175,373,182,360,195,345,202,351,209,348,220,346,232,357,244,381,251,400,254,413,249,432,225,453,205,459,181,456" shape="poly">
                                            <area target="" @click.prevent="ccDetails" alt="Chattogram City Corporation" title="Chattogram City Corporation" href="/mahanagar/2" coords="312,347,300,373,311,389,323,411,328,443,330,468,337,491,346,504,349,519,369,549,376,549,368,514,368,494,374,492,378,497,388,502,395,510,401,500,395,470,396,428,383,359,377,350,376,323,368,286,350,282,340,285,336,302,326,319,321,339" shape="poly">
                                            <area target="" @click.prevent="ccDetails" alt="Cumilla City Corporation" title="Cumilla City Corporation" href="/mahanagar/3" coords="231,316,242,296,249,272,267,241,283,238,289,253,285,264,278,287,285,308,290,322,301,328,309,344,296,376,288,380,279,396,256,390,238,357,230,339" shape="poly">
                                            <area target="" @click.prevent="ccDetails" alt="Dhaka North City Corporation" title="Dhaka North City Corporation" href="/mahanagar/4" coords="164,251,201,268,158,342,151,318,144,299,123,281,128,267,144,275,154,269" shape="poly">
                                            <area target="" @click.prevent="ccDetails" alt="Dhaka South City Corporation" title="Dhaka South City Corporation" href="/mahanagar/5" coords="160,344,203,268,241,288,227,310,228,334,218,345,202,346,193,341,176,363" shape="poly">
                                            <area target="" @click.prevent="ccDetails" alt="Gazipur City Corporation" title="Gazipur City Corporation" href="/mahanagar/6" coords="165,249,163,236,162,208,171,196,183,189,190,194,196,216,212,233,223,231,201,265" shape="poly">
                                            <area target="" @click.prevent="ccDetails" alt="Khulna City Corporation" title="Khulna City Corporation" href="/mahanagar/7" coords="70,240,85,248,92,244,103,257,119,264,125,269,120,277,123,287,136,295,143,303,150,322,152,334,159,345,174,364,172,376,173,392,168,397,166,415,170,439,171,446,158,455,140,464,120,473,102,458,102,435,82,346,91,329,70,323,75,307,60,292,61,268,71,264,71,253" shape="poly">
                                            <area target="" @click.prevent="ccDetails" alt="Mymensingh City Corporation" title="Mymensingh City Corporation" href="/mahanagar/8" coords="162,136,159,137,158,146,153,158,153,176,163,191,163,199,182,187,189,187,196,202,201,217,209,224,220,229,227,231,227,221,224,214,234,213,243,211,250,206,271,202,278,198,271,188,271,180,257,179,256,153,209,153,185,145,172,141,162,136" shape="poly">
                                            <area target="" @click.prevent="ccDetails" alt="Narayangonj City Corporation" title="Narayangonj City Corporation" href="/mahanagar/9" coords="278,202,245,209,226,216,228,229,226,235,203,265,241,286,263,244,277,234,283,223" shape="poly">
                                            <area target="" @click.prevent="ccDetails" alt="Rajshahi City Corporation" title="Rajshahi City Corporation" href="/mahanagar/10" coords="73,236,84,246,95,240,112,259,129,264,145,271,156,259,163,243,158,230,162,193,155,184,150,172,150,155,120,152,114,144,95,141,91,150,51,150,38,179,25,173,15,196,24,213" shape="poly">
                                            <area target="" @click.prevent="ccDetails" alt="Rangpur City Corporation" title="Rangpur City Corporation" href="/mahanagar/11" coords="93,140,115,139,122,149,152,151,160,133,167,114,162,91,165,78,150,57,144,66,141,81,122,74,105,63,105,47,93,39,93,58,80,54,46,22,41,36,53,41,26,66,20,87,26,98,43,100,52,115,65,125,77,123,82,128" shape="poly">
                                            <area target="" @click.prevent="ccDetails" alt="Sylhet City Corporation" title="Sylhet City Corporation" href="/mahanagar/12" coords="258,152,261,177,275,179,279,196,287,223,277,235,286,241,292,257,311,249,325,241,337,241,350,225,365,184,365,178,373,181,385,178,379,166,360,155,341,150,316,154,289,150" shape="poly">
                                        </map>
                                    </div>
                                    <div class="col-6">

                                        <!-- Image Map Generated by http://www.image-map.net/ -->
                                        <img src="assets/img/bd-map.png" usemap="#image-map-bd">

                                        <map name="image-map-bd">
                                            <area target="" @click.prevent="details(1)" alt="Barguna" title="Barguna" href="/district/1" coords="187,451,203,430,211,439,222,440,230,447,231,455,240,464,234,479,211,485,190,470" shape="poly">
                                            <area target="" @click.prevent="details(2)" alt="Barishal" title="Barishal" href="/district/2" coords="199,377,203,370,209,361,216,371,225,367,241,361,254,372,254,379,244,389,240,408,233,413,219,414,231,402,219,390,211,388,202,386" shape="poly">
                                            <area target="" @click.prevent="details(3)" alt="Bhola" title="Bhola" href="/district/3" coords="244,405,247,390,256,388,270,403,277,417,285,426,285,450,268,481,251,477,251,463,253,451,249,439,254,424" shape="poly">
                                            <area target="" @click.prevent="details(4)" alt="Jalokathi" title="Jalokathi" href="/district/4" coords="212,391,219,394,229,404,218,412,204,431,201,424,201,407" shape="poly">
                                            <area target="" @click.prevent="details(5)" alt="Patuakhali" title="Patuakhali" href="/district/5" coords="210,431,216,418,229,417,235,421,237,414,245,410,251,426,247,437,248,446,250,462,241,462,233,453,233,444,225,438,215,437" shape="poly">
                                            <area target="" @click.prevent="details(6)" alt="Pirojpur" title="Pirojpur" href="/district/6" coords="188,397,189,392,190,382,196,381,203,389,210,392,205,400,199,409,202,419,197,427,198,436,187,448,187,427,196,416,189,411,188,397" shape="poly">
                                            <area target="" @click.prevent="details(7)" alt="Bandharban" title="Bandharban" href="/district/7" coords="381,466,391,459,386,449,388,428,403,429,411,437,416,453,426,469,425,491,430,512,434,523,425,524,421,517,411,516,404,510,397,514,391,522,390,533,385,516,388,507,389,499,383,490,389,481,381,476" shape="poly">
                                            <area target="" @click.prevent="details(8)" alt="Brahamanbaria" title="Brahamanbaria" href="/district/8" coords="288,252,298,244,308,252,308,267,315,272,307,276,306,284,299,302,284,290,262,300,264,289,278,281,284,274,282,265" shape="poly">
                                            <area target="" @click.prevent="details(9)" alt="Chandpur" title="Chandpur" href="/district/9" coords="243,330,247,321,256,320,259,330,270,324,285,343,284,353,271,351,252,367,243,358,249,341" shape="poly">
                                            <area target="" @click.prevent="details(10)" alt="Chittagong" title="Chittagong" href="/district/10" coords="321,387,338,371,347,368,350,381,361,393,366,401,371,412,374,403,382,409,381,420,387,427,385,438,384,451,387,458,383,464,367,471,360,464,350,426,341,422,329,433,318,417,324,403,336,395" shape="poly">
                                            <area target="" @click.prevent="details(11)" alt="Comilla" title="Comilla" href="/district/11" coords="251,307,268,299,284,292,299,304,299,314,306,323,312,336,315,348,312,354,307,358,297,358,285,354,287,342,280,332,271,322,261,329,259,321,258,314" shape="poly">
                                            <area target="" @click.prevent="details(12)" alt="Cox's Bazar" title="Cox's Bazar" href="/district/12" coords="358,465,366,472,377,469,379,478,385,481,380,491,385,500,383,514,387,533,390,541,405,576,401,580,391,558,375,538,374,528,369,515,359,506,359,492,354,483" shape="poly">
                                            <area target="" @click.prevent="details(13)" alt="Feni" title="Feni" href="/district/13" coords="307,362,315,357,322,360,319,347,320,339,328,347,334,361,338,368,321,385,313,378,309,372" shape="poly">
                                            <area target="" @click.prevent="details(14)" alt="Khagrachari" title="Khagrachari" href="/district/14" coords="349,368,358,361,352,341,366,327,369,321,367,303,378,309,382,327,376,333,382,339,383,350,387,356,378,358,381,369,375,375,368,379,370,391,366,398,357,385,351,379" shape="poly">
                                            <area target="" @click.prevent="details(15)" alt="Lakshmipur" title="Lakshmipur" href="/district/15" coords="253,368,272,353,281,354,273,363,283,370,279,378,277,388,282,396,284,411,275,408,265,392,260,387,260,379" shape="poly">
                                            <area target="" @click.prevent="details(16)" alt="Noakhali" title="Noakhali" href="/district/16" coords="275,362,284,354,291,360,307,363,307,376,313,381,318,391,312,405,306,427,299,454,291,459,285,454,288,426,290,407,279,387,285,370" shape="poly">
                                            <area target="" @click.prevent="details(17)" alt="Rangamati" title="Rangamati" href="/district/17" coords="379,307,386,300,395,302,399,312,406,334,409,347,405,372,414,383,420,403,424,437,426,467,420,457,414,437,405,427,392,427,384,422,383,406,378,403,370,406,368,399,374,391,371,380,384,369,380,361,388,354,384,348,385,338,379,332,385,324" shape="poly">
                                            <area target="" @click.prevent="details(18)" alt="Dhaka" title="Dhaka" href="/district/18" coords="199,270,208,267,214,270,225,268,226,279,236,282,234,296,233,308,219,302,210,316,195,305,200,297,212,296,207,287" shape="poly">
                                            <area target="" @click.prevent="details(19)" alt="Faridpur" title="Faridpur" href="/district/19" coords="152,312,172,310,173,303,182,299,189,307,197,310,210,319,203,326,196,334,183,332,175,336,168,346,160,335,161,324" shape="poly">
                                            <area target="" @click.prevent="details(20)" alt="Gazipur" title="Gazipur" href="/district/20" coords="211,264,220,251,221,244,234,239,243,247,251,245,255,258,249,265,250,276,239,274,234,280,227,275,225,265" shape="poly">
                                            <area target="" @click.prevent="details(21)" alt="Gopalgonj" title="Gopalgonj" href="/district/21" coords="167,348,178,336,184,335,194,335,192,345,188,353,205,362,195,379,183,381,179,368,172,361" shape="poly">
                                            <area target="" @click.prevent="details(22)" alt="Kishoregonj" title="Kishoregonj" href="/district/22" coords="254,242,251,231,247,223,260,225,267,215,293,211,302,218,296,224,304,232,299,239,295,245,284,252,283,258,281,264,271,256,266,246" shape="poly">
                                            <area target="" @click.prevent="details(23)" alt="Madaripur" title="Madaripur" href="/district/23" coords="191,353,198,342,197,336,211,319,217,325,211,330,215,341,217,348,226,355,224,367,217,368,214,361,206,360" shape="poly">
                                            <area target="" @click.prevent="details(24)" alt="Manikganj" title="Manikganj" href="/district/24" coords="170,283,170,272,175,268,180,274,196,271,205,285,211,290,213,296,202,295,196,299,194,306,184,297" shape="poly">
                                            <area target="" @click.prevent="details(25)" alt="Munshigonj" title="Munshigonj" href="/district/25" coords="211,317,220,304,232,310,249,309,256,318,246,320,241,329,220,323" shape="poly">
                                            <area target="" @click.prevent="details(26)" alt="Narayangonj" title="Narayangonj" href="/district/26" coords="237,282,241,274,260,290,259,299,253,302,246,308,236,313,236,304" shape="poly">
                                            <area target="" @click.prevent="details(27)" alt="Narsinghdi" title="Narsinghdi" href="/district/27" coords="248,279,251,274,252,265,256,259,253,245,262,250,278,265,279,275,271,283,260,288" shape="poly">
                                            <area target="" @click.prevent="details(28)" alt="Rajbari" title="Rajbari" href="/district/28" coords="139,301,134,293,140,281,153,290,170,287,182,298,171,303,171,309,150,310" shape="poly">
                                            <area target="" @click.prevent="details(29)" alt="Tangail" title="Tangail" href="/district/29" coords="175,218,186,205,202,198,208,212,207,218,214,230,219,251,209,264,201,267,188,270,176,269,179,262,174,233" shape="poly">
                                            <area target="" @click.prevent="details(30)" alt="Shariatpur" title="Shariatpur" href="/district/30" coords="214,330,219,325,233,329,242,332,247,344,241,358,235,361,228,361,229,351,221,346,218,339" shape="poly">
                                            <area target="" @click.prevent="details(31)" alt="Bagerhat" title="Bagerhat" href="/district/31" coords="154,400,165,383,175,369,178,382,189,384,187,393,180,396,187,401,189,416,185,433,184,457,185,476,166,487,149,492,156,460,159,449,155,441,162,425" shape="poly">
                                            <area target="" @click.prevent="details(32)" alt="Chuadanga" title="Chuadanga" href="/district/31" coords="75,307,80,302,89,297,95,287,107,296,104,309,99,314,100,324,93,327,86,327,81,318" shape="poly">
                                            <area target="" @click.prevent="details(33)" alt="Jessore" title="Jessore" href="/district/33" coords="99,345,105,337,113,338,119,342,130,335,141,343,140,353,145,365,135,375,135,382,128,380,120,386,118,372,98,374,94,361,97,353" shape="poly">
                                            <area target="" @click.prevent="details(34)" alt="Jhenaidha" title="Jhenaidha" href="/district/34" coords="85,330,95,327,102,322,102,314,107,305,109,298,132,294,136,304,130,322,128,335,120,341,111,334,103,336,97,344,83,341" shape="poly">
                                            <area target="" @click.prevent="details(35)" alt="Khulna" title="Khulna" href="/district/35" coords="129,383,137,384,138,375,147,367,169,371,164,383,152,401,160,425,155,441,155,457,148,485,147,494,133,493,136,464,133,435,129,426,130,405,135,392" shape="poly">
                                            <area target="" @click.prevent="details(36)" alt="Kushtia" title="Kushtia" href="/district/36" coords="89,275,85,265,85,254,95,261,106,259,113,273,127,275,137,280,134,291,120,294,109,295,98,285" shape="poly">
                                            <area target="" @click.prevent="details(37)" alt="Magura" title="Magura" href="/district/37" coords="131,331,135,320,140,304,151,315,158,323,159,337,145,342,136,337" shape="poly">
                                            <area target="" @click.prevent="details(38)" alt="Meherpur" title="Meherpur" href="/district/38" coords="74,307,77,300,87,294,94,284,83,272,75,282,69,283,69,294" shape="poly">
                                            <area target="" @click.prevent="details(39)" alt="Narail" title="Narail" href="/district/39" coords="143,357,144,343,159,338,166,347,174,366,162,367,150,367" shape="poly">
                                            <area target="" @click.prevent="details(40)" alt="Satkhira" title="Satkhira" href="/district/40" coords="99,378,115,374,116,387,127,383,132,392,129,400,127,412,127,429,131,438,134,463,130,495,111,483,110,469,113,449,103,433,101,388" shape="poly">
                                            <area target="" @click.prevent="details(41)" alt="Jamalpur" title="Jamalpur" href="/district/41" coords="164,170,172,151,173,139,180,137,184,147,186,163,185,173,187,179,211,186,205,194,195,199,185,200,183,208,176,214,177,195,169,191,167,178" shape="poly">
                                            <area target="" @click.prevent="details(42)" alt="Mymensingh" title="Mymensingh" href="/district/42" coords="217,155,215,186,205,197,209,207,210,220,217,228,217,238,219,245,224,240,235,237,245,245,252,241,247,228,246,221,253,223,261,223,264,214,254,205,256,194,245,194,236,170,247,167,249,156,232,157" shape="poly">
                                            <area target="" @click.prevent="details(43)" alt="Netrakona" title="Netrakona" href="/district/43" coords="240,172,251,169,251,158,277,160,278,181,288,186,295,198,301,207,289,210,266,212,257,204,259,193,247,190" shape="poly">
                                            <area target="" @click.prevent="details(44)" alt="Sherpur" title="Sherpur" href="/district/44" coords="187,145,188,164,188,175,214,184,216,156" shape="poly">
                                            <area target="" @click.prevent="details(45)" alt="Bogra" title="Bogra" href="/district/45" coords="111,186,133,167,161,170,166,180,166,188,160,201,153,205,157,214,143,215,131,209,122,206,113,194,107,194" shape="poly">
                                            <area target="" @click.prevent="details(46)" alt="Chapai Nawabganj" title="Chapai Nawabganj" href="/district/46" coords="47,183,55,178,52,188,58,198,61,203,45,216,53,233,36,225,22,205,33,181,41,177" shape="poly">
                                            <area target="" @click.prevent="details(47)" alt="Jaipurhat" title="Jaipurhat" href="/district/47" coords="101,158,106,169,113,186,132,168,124,156,127,150,106,146" shape="poly">
                                            <area target="" @click.prevent="details(48)" alt="Naogaon" title="Naogaon" href="/district/48" coords="56,176,59,164,61,154,100,156,108,180,109,187,104,198,113,197,120,207,116,217,105,215,98,208,90,204,79,209,66,201,59,195,54,188,62,181" shape="poly">
                                            <area target="" @click.prevent="details(49)" alt="Natore" title="Natore" href="/district/49" coords="97,255,100,245,94,238,103,216,114,221,120,211,127,215,134,216,128,228,134,237,123,250,111,255,104,256" shape="poly">
                                            <area target="" @click.prevent="details(50)" alt="Pabna" title="Pabna" href="/district/50" coords="110,259,122,254,135,238,145,247,160,262,168,269,168,285,157,287,144,280,136,273,125,272,114,271" shape="poly">
                                            <area target="" @click.prevent="details(51)" alt="Rajshahi" title="Rajshahi" href="/district/51" coords="56,233,49,222,65,204,79,211,90,206,102,215,96,225,93,240,96,246,94,258,84,252,82,240" shape="poly">
                                            <area target="" @click.prevent="details(52)" alt="Sirajgonj" title="Sirajgonj" href="/district/52" coords="134,235,130,227,137,215,158,216,158,205,167,195,174,200,171,229,175,252,177,263,169,267,164,262,155,256,152,249,143,241" shape="poly">
                                            <area target="" @click.prevent="details(53)" alt="Dinajpur" title="Dinajpur" href="/district/53" coords="59,110,57,94,64,92,67,85,73,78,85,79,92,90,99,106,114,121,131,150,100,145,94,136,94,126,88,122,78,128,66,122" shape="poly">
                                            <area target="" @click.prevent="details(54)" alt="Gaibandha" title="Gaibandha" href="/district/54" coords="134,148,147,127,145,119,154,115,166,125,170,137,171,148,162,168,150,167,138,163,131,163,126,155" shape="poly">
                                            <area target="" @click.prevent="details(55)" alt="Kurigram" title="Kurigram" href="/district/55" coords="153,78,159,79,162,71,161,64,164,57,170,59,184,83,181,97,186,116,179,136,169,134,167,122,156,113,150,96,157,89" shape="poly">
                                            <area target="" @click.prevent="details(56)" alt="Lalmonirhat" title="Lalmonirhat" href="/district/56" coords="111,55,117,63,118,74,125,83,140,94,149,95,154,92,151,80,133,72,123,61,123,46,106,35,102,40" shape="poly">
                                            <area target="" @click.prevent="details(57)" alt="Nilphamari" title="Nilphamari" href="/district/57" coords="93,49,93,58,91,72,87,79,99,101,123,84,116,74,116,65,108,54,99,49" shape="poly">
                                            <area target="" @click.prevent="details(58)" alt="Panchagarh" title="Panchagarh" href="/district/58" coords="51,54,61,61,67,58,76,66,78,72,81,77,89,72,91,65,91,59,89,49,64,27,58,17,53,32,64,36,68,42,58,48" shape="poly">
                                            <area target="" @click.prevent="details(59)" alt="Rangpur" title="Rangpur" href="/district/59" coords="101,104,124,86,148,99,154,111,143,119,145,127,133,147,117,120" shape="poly">
                                            <area target="" @click.prevent="details(60)" alt="Thakurgaon" title="Thakurgaon" href="/district/60" coords="36,66,42,59,51,55,58,62,66,60,74,68,72,74,63,85,55,92,55,103,45,100,32,97,29,89,34,76" shape="poly">
                                            <area target="" @click.prevent="details(61)" alt="Habiganj" title="Habiganj" href="/district/61" coords="302,222,314,205,337,207,338,217,332,228,337,250,341,253,337,261,318,258,317,271,311,268,311,249,299,243,307,231" shape="poly">
                                            <area target="" @click.prevent="details(62)" alt="Mauluvibazar" title="Mauluvibazar" href="/district/62" coords="342,212,351,211,361,207,369,208,382,196,394,189,396,199,394,206,390,221,379,233,369,237,361,256,350,248,351,256,341,250,336,227,345,218" shape="poly">
                                            <area target="" @click.prevent="details(63)" alt="Sunamganj" title="Sunamganj" href="/district/63" coords="280,157,280,179,291,186,303,204,304,212,315,203,338,204,343,175,343,160,333,156,315,159,297,154" shape="poly">
                                            <area target="" @click.prevent="details(64)" alt="Sylhet" title="Sylhet" href="/district/64" coords="345,159,345,184,340,207,345,211,356,205,370,206,378,199,381,194,387,193,393,189,392,183,398,183,409,187,414,183,412,176,407,170,391,162,380,156,364,155" shape="poly">
                                            
                                        </map>
                                    </div>
                                </div>
                                

                            </div>
                        </div>
                        
                        
                    </div>
                </div>
            </div>
        </div>

        <!-- Modal -->
        <div class="modal fade" id="detailsModal" tabindex="-1" role="dialog" aria-labelledby="detailsModal" aria-hidden="true">
            <div class="modal-dialog modal-xl" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="districtDetailsModelLabel">  District: {{distExecutive.district_name}}</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>

                        <div class="modal-body">

                            <ul class="nav nav-tabs nav-fill mb-3" id="myTab" role="tablist">
                                <li class="nav-item">
                                    <a class="nav-link active" id="info-tab" data-toggle="tab" href="#info" role="tab" aria-controls="info" aria-selected="true">Basic Info</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" id="executive-tab" data-toggle="tab" href="#executive" role="tab" aria-controls="executive" aria-selected="true">Executive</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" id="council-tab" data-toggle="tab" href="#council" role="tab" aria-controls="council" aria-selected="true">Council </a>
                                </li>
                                <!-- <li class="nav-item">
                                    <a class="nav-link" id="upazilla-tab" data-toggle="tab" href="#upazilla" role="tab" aria-controls="upazilla" aria-selected="false">Upazilla</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" id="pourashava-tab" data-toggle="tab" href="#pourashava" role="tab" aria-controls="pourashava" aria-selected="false">Pourashava</a>
                                </li> -->
                            </ul>
                            <div class="tab-content" id="myTabContent">
                                <div class="tab-pane fade show active" id="info" role="tabpanel" aria-labelledby="info-tab">
                                    <div class="row justify-content-md-center">
                                        <div class="col-5">
                                            <div v-if="distExecutive.district_image" class="map"><img :src="getImage(distExecutive.district_image)" width="100%" height="400" alt="District image" ></div>
                                            <div v-else class="map"><img src="assets/img/dhaka-map.png" height="400" alt=""></div>
                                        </div>
                                        <div class="col-5">
                                            <div class="district-info mt-30">
                                                <h2>{{distExecutive.district_name}}</h2>
                                                <table width="400">
                                                    <tr>
                                                        <td>Area:</td>
                                                        <td> 15000 Sq. Mt.</td>
                                                    </tr>
                                                    <tr>
                                                        <td>Population:</td>
                                                        <td>3,00,000,000</td>
                                                    </tr>
                                                    <tr>
                                                        <td>Density:</td>
                                                        <td>1500000 / Km</td>
                                                    </tr>
                                                    <tr>
                                                        <td>Eduction Rate:</td>
                                                        <td>80%</td>
                                                    </tr>
                                                    <tr>
                                                        <td>Seat:</td>
                                                        <td>20</td>
                                                    </tr>
                                                    <tr>
                                                        <td>Main opposition:</td>
                                                        <td>Awamileague</td>
                                                    </tr>
                                                </table>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="tab-pane fade show" id="executive" role="tabpanel" aria-labelledby="executive-tab">
                                    
                                    <div class="row">
                                        <div class="col-2">
                                            <div v-for="(committees, index) in distExecutive" :key="index" class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
                                                <a v-for="(committee, i) in committees" :key="i" :class="'nav-link ' + getTabClass(i)" :id="'v-pills-'+i+'-ex-tab'" data-toggle="pill" :href="'#v-pills-'+i+'-ex'" role="tab" :aria-controls="'v-pills-'+i+'-ex'" :aria-selected="true">{{i.charAt(0).toUpperCase() + i.slice(1).split('-')[0]}}</a>
                                            </div>
                                        </div>
                                        <div class="col-10">
                                            <div v-for="(committees, index) in distExecutive" :key="index" class="tab-content" id="v-pills-tabContent">
                                                <div v-for="(committee, i) in committees" :key="i" :class="'tab-pane fade '+ getTabConClass(i)+' content-overflow'" :id="'v-pills-'+i+'-ex'" role="tabpanel" :aria-labelledby="'v-pills-'+i+'ex-tab'">
                                                    <table id="example1" class="table table-bordered table-striped dataTable bigData" role="grid" aria-describedby="example1_info">
                                                        <thead>
                                                            <tr role="row">
                                                                <th class="sorting" style="width: 200px;">
                                                                    Name
                                                                </th>
                                                                <!-- <th class="sorting" style="width: 50px;">
                                                                    Image
                                                                </th> -->
                                                                <th class="sorting" style="width: 150px;">
                                                                    Mobile
                                                                </th>
                                                                <th class="sorting" style="width: 50px;">
                                                                    District
                                                                </th>
                                                                <th class="sorting" style="width: 150px;">
                                                                    Designation
                                                                </th>
                                                            </tr>
                                                        </thead>

                                                        <tbody>
                                                            
                                                            <tr v-for="(item, x) in committee" :key="x">
                                                                <td>{{item.member_name}}</td>
                                                                <td>{{item.mobile}}</td>
                                                                <td>{{item.district_name}}</td>
                                                                <!-- <td>{{item.designation}}</td> -->
                                                                <td v-if="item.post_committee === 'Zilla Executive'">{{item.designation}}</td>
                                                                <td v-else>Member</td>
                                                            </tr>
                                                        </tbody>
                                                    </table>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                </div>

                                <div class="tab-pane fade" id="council" role="tabpanel" aria-labelledby="council-tab">
                                    
                                    <div class="row">
                                        <div class="col-2">
                                            <div v-for="(committees, index) in distCouncil" :key="index" class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
                                                <a v-for="(committee, i) in committees" :key="i" :class="'nav-link ' + getTabClass(i)" :id="'v-pills-'+i+'-cl-tab'" data-toggle="pill" :href="'#v-pills-'+i+'-cl'" role="tab" :aria-controls="'v-pills-'+i+'-cl'" aria-selected="true">{{i.charAt(0).toUpperCase() + i.slice(1).split('-')[0]}}</a>
                                            </div>
                                        </div>
                                        <div class="col-10">
                                            <div v-for="(committees, index) in distCouncil" :key="index" class="tab-content" id="v-pills-tabContent">
                                                <div v-for="(committee, i) in committees" :key="i" :class="'tab-pane fade '+ getTabConClass(i)+' content-overflow'" :id="'v-pills-'+i+'-cl'" role="tabpanel" :aria-labelledby="'v-pills-'+i+'cl-tab'">
                                                    <table id="example1" class="table table-bordered table-striped dataTable bigData" role="grid" aria-describedby="example1_info">
                                                        <thead>
                                                            <tr role="row">
                                                                <th class="sorting" style="width: 200px;">
                                                                    Name
                                                                </th>
                                                                <!-- <th class="sorting" style="width: 50px;">
                                                                    Image
                                                                </th> -->
                                                                <th class="sorting" style="width: 150px;">
                                                                    Mobile
                                                                </th>
                                                                <th class="sorting" style="width: 50px;">
                                                                    District
                                                                </th>
                                                                <th class="sorting" style="width: 150px;">
                                                                    Designation
                                                                </th>
                                                            </tr>
                                                        </thead>

                                                        <tbody>
                                                            
                                                            <tr v-for="(item, x) in committee" :key="x">
                                                                <td>{{item.member_name}}</td>
                                                                <td>{{item.mobile}}</td>
                                                                <td>{{item.district_name}}</td>
                                                                <!-- <td>{{item.designation}}</td> -->
                                                                <td v-if="item.post_committee === 'Zilla Council'">{{item.designation}}</td>
                                                                <td v-else>Member</td>
                                                            </tr>
                                                        </tbody>
                                                    </table>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    
                                </div>

                                <!-- <div class="tab-pane fade" id="upazilla" role="tabpanel" aria-labelledby="upazilla-tab">
                                    
                                    Upazilla
                                    
                                </div>

                                <div class="tab-pane fade" id="pourashava" role="tabpanel" aria-labelledby="pourashava-tab">
                                    
                                    Pourashava
                                    
                                </div> -->
                                
                            </div>
                        </div>

                        <div class="modal-footer">
                            <button type="button" class="btn btn-danger btn-sm" data-dismiss="modal">Close</button>
                        </div>
                </div>
            </div>
        </div>
        <!-- End Modal -->

    </div>
</template>

<script>
    export default {
        mounted() {
            console.log('Component mounted.')
        },

        data(){
            return {
                distInfo:{},
                distExecutive:{},
                distCouncil:{},
            }
        },

        methods: {
            details(id){
                axios.get('api/dashboard/' + id).then(({ data }) => (
                    this.distInfo = data[0],
                    this.distExecutive = data[1],
                    this.distCouncil = data[2]
                ));
                $('#detailsModal').modal('show');                
            },

            getTabClass(str){
                if(str == 'mainstream-show-active'){
                    let cls = str.split('-');
                    console.log(cls[0]);
                    return cls[2];
                }

                if(str == 'word-1-show-active'){
                    let cls = str.split('-');
                    console.log(cls[0]);
                    return cls[3];
                }
            },

            getTabConClass(str){
                if(str == 'mainstream-show-active'){
                    let cls = str.split('-');
                    console.log(cls[0]);
                    return cls[1]+' '+ cls[2];
                }
            },

            getImage(img){
                return "assets/img/district/" + img;
            }

        },

        created(){

        }
    }
</script>
